# Generated by Django 4.2.4 on 2023-09-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Telegram_Analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_link", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
